"use client";
import {useState} from "react";import {useRouter} from "next/navigation";
import {useLocale} from "@/components/LocaleController";
import {translate} from "@/lib/i18n";
export function LeadForm({kind="contact"}:{kind?:"contact"|"valuation"}){
 const [status,setStatus]=useState<React.ReactNode>("");const router=useRouter();const {locale}=useLocale();const tr=(text:string)=>translate(text,locale);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;setStatus(tr("Envoi en cours…"));let res:Response;try{const data=Object.fromEntries(new FormData(form));res=await fetch(`/api/${kind}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(data)});}catch{setStatus(tr("La connexion a été interrompue. Réessayez dans un instant."));return;}const result=await res.json().catch(()=>null);if(!res.ok){setStatus(tr(result?.code==="invalid_payload"?"Les informations transmises sont incomplètes.":"L’envoi n’a pas abouti. Réessayez dans un instant."));return;}setStatus(<span className="form-success">{tr("Demande bien enregistrée.")}</span>);form.reset();if(kind==="valuation")router.push("/grazie");}
 return <form onSubmit={submit}><input className="honeypot" name="website" tabIndex={-1} autoComplete="off"/><div className="field-row"><label>Prénom<input required name="name" maxLength={80}/></label><label>Nom<input required name="surname" maxLength={80}/></label></div><label>E-mail<input required name="email" type="email" maxLength={160}/></label>{kind==="contact"&&<><div className="field-row"><label>Vous êtes<select name="profile" required><option value="">Sélectionner</option><option>Propriétaire</option><option>Investisseur</option><option>Voyageur</option><option>Partenaire</option></select></label><label>Objet de la demande<select name="subject" required><option value="">Sélectionner</option><option>Mettre un bien en gestion</option><option>Obtenir une estimation</option><option>Demander un service</option><option>Proposer un partenariat</option></select></label></div><div className="field-row"><label>Localisation du bien<input name="city" placeholder="Gênes, Portofino…"/></label><label>Type de bien<select name="propertyType"><option>Non concerné</option><option>Appartement</option><option>Attique</option><option>Villa</option><option>Maison indépendante</option></select></label></div><div className="field-row"><label>Nombre de biens<input name="propertyCount" type="number" min="1"/></label><label>Délai souhaité<select name="timeline"><option>Dès que possible</option><option>Sous 1 à 3 mois</option><option>Sous 3 à 6 mois</option><option>Je me renseigne</option></select></label></div></>}{kind==="valuation"&&<><div className="field-row"><label>Ville<input required name="city"/></label><label>Type de bien<select name="type"><option>Appartement</option><option>Attique</option><option>Villa</option><option>Maison indépendante</option></select></label></div><div className="field-row"><label>Surface en m²<input name="area" type="number" min="20"/></label><label>Chambres<input name="bedrooms" type="number" min="1"/></label></div><label>Objectif principal<select name="objective"><option>Déléguer la gestion</option><option>Optimiser les revenus</option><option>Améliorer l’expérience des voyageurs</option><option>Protéger et entretenir le bien</option><option>Recevoir une évaluation</option></select></label></>}<label>Décrivez votre besoin<textarea required name="message" maxLength={2000} placeholder="Parlez-nous du bien, de sa situation actuelle et de votre objectif."/></label><label><span><input required type="checkbox" name="consent"/> J’accepte que mes données soient utilisées afin d’être recontacté au sujet de ma demande.</span></label><button className="button" type="submit">{kind==="valuation"?"Envoyer la demande confidentielle":"Envoyer le message"}</button><div role="status" className="form-status">{status}</div></form>;
}
