"use client";
import {useState} from "react";import {useRouter} from "next/navigation";
import {useLocale} from "@/components/LocaleController";
import {translate} from "@/lib/i18n";
const stepLabels=["Coordonnées","Propriété","Objectifs"];
export function ValuationForm(){
 const [step,setStep]=useState(0);const [status,setStatus]=useState<React.ReactNode>("");const router=useRouter();const {locale}=useLocale();const tr=(text:string)=>translate(text,locale);
 function next(event:React.MouseEvent<HTMLButtonElement>){const form=event.currentTarget.form;if(!form)return;const fields=Array.from(form.querySelectorAll<HTMLElement>(`[data-step="${step}"] input, [data-step="${step}"] select, [data-step="${step}"] textarea`));if(fields.every(f=>!(f instanceof HTMLInputElement||f instanceof HTMLSelectElement||f instanceof HTMLTextAreaElement)||f.reportValidity()))setStep(v=>Math.min(v+1,2));}
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setStatus(tr("Envoi en cours…"));const form=event.currentTarget;const formData=new FormData(form);const payload={...Object.fromEntries(formData),amenities:formData.getAll("amenities"),services:formData.getAll("services")};let response:Response;try{response=await fetch("/api/valuation",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});}catch{setStatus(tr("La connexion a été interrompue. Réessayez dans un instant."));return;}const result=await response.json().catch(()=>null);if(!response.ok){setStatus(tr(result?.code==="invalid_payload"?"Les informations transmises sont incomplètes.":"L’envoi n’a pas abouti. Réessayez dans un instant."));return;}setStatus(<span className="form-success">{tr("Demande bien enregistrée.")}</span>);form.reset();router.push("/grazie");}
 return <form onSubmit={submit}>
  <div className="form-progress" aria-label={locale==="it"?`Fase ${step+1} di 3`:locale==="en"?`Step ${step+1} of 3`:`Étape ${step+1} sur 3`}>{stepLabels.map((label,index)=><span key={label} className={index<=step?"active":""}>{index+1}<small>{label}</small></span>)}</div>
  <fieldset data-step="0" hidden={step!==0}><legend>Vos coordonnées</legend><p className="form-hint">Ces informations servent uniquement à organiser un premier échange confidentiel par e-mail.</p><div className="field-row"><label>Prénom<input required name="name" maxLength={80} autoComplete="given-name"/></label><label>Nom<input required name="surname" maxLength={80} autoComplete="family-name"/></label></div><div className="field-row"><label>E-mail<input required name="email" type="email" maxLength={160} autoComplete="email"/></label><label>Vous êtes<select name="profile" required><option value="">Sélectionner</option><option>Propriétaire occupant</option><option>Propriétaire bailleur</option><option>Investisseur</option><option>Mandataire</option></select></label></div></fieldset>
  <fieldset data-step="1" hidden={step!==1}><legend>La propriété</legend><p className="form-hint">Plus le descriptif est précis, plus notre premier retour pourra être utile.</p><div className="field-row"><label>Adresse<input required name="address" autoComplete="street-address"/></label><label>Ville<input required name="city"/></label></div><div className="field-row"><label>Type de bien<select name="type"><option>Appartement</option><option>Attique</option><option>Villa</option><option>Maison indépendante</option></select></label><label>Surface en m²<input required name="area" type="number" min="20"/></label></div><div className="field-row"><label>Chambres<input required name="bedrooms" type="number" min="1"/></label><label>Salles de bain<input required name="bathrooms" type="number" min="1"/></label></div><div className="field-row"><label>Capacité d’accueil<input name="capacity" type="number" min="1"/></label><label>Niveau de finition<select name="finish"><option>À préparer</option><option>Soigné</option><option>Premium</option><option>Luxe</option></select></label></div><div className="amenities-checks"><span>Équipements présents</span>{["Vue mer","Terrasse","Piscine","Parking","Climatisation","Ascenseur"].map(item=><label key={item}><input type="checkbox" name="amenities" value={item}/>{item}</label>)}</div></fieldset>
  <fieldset data-step="2" hidden={step!==2}><legend>Votre projet</legend><p className="form-hint">Nous cherchons à comprendre la situation actuelle, pas uniquement les caractéristiques du bien.</p><div className="field-row"><label>Bien déjà loué ?<select name="currentlyRented"><option>Non</option><option>Oui, occasionnellement</option><option>Oui, régulièrement</option></select></label><label>Disponibilité annuelle<select name="availability"><option>Jusqu’à 3 mois</option><option>3 à 6 mois</option><option>6 à 9 mois</option><option>Plus de 9 mois</option></select></label></div><div className="field-row"><label>Taux d’occupation actuel<select name="currentOccupancy"><option>Inconnu</option><option>Moins de 30 %</option><option>30 à 50 %</option><option>50 à 70 %</option><option>Plus de 70 %</option></select></label><label>Revenu annuel actuel<input name="currentRevenue" type="number" min="0" placeholder="Facultatif"/></label></div><label>Objectif principal<select name="objective"><option>Déléguer la gestion</option><option>Optimiser les revenus</option><option>Améliorer l’expérience des voyageurs</option><option>Protéger et entretenir le bien</option><option>Lancer la location</option></select></label><div className="amenities-checks"><span>Services recherchés</span>{["Gestion Sérénité","Solution Privilège multi-biens","Accueil voyageurs","Ménage et linge","Maintenance","Optimisation tarifaire"].map(item=><label key={item}><input type="checkbox" name="services" value={item}/>{item}</label>)}</div><label>Décrivez votre situation et vos priorités<textarea required name="message" maxLength={2000} placeholder="Disponibilités, contraintes, historique de location, attentes particulières…"/></label><label><span><input required type="checkbox" name="consent"/> J’accepte que mes données soient utilisées afin d’être recontacté au sujet de ma demande.</span></label></fieldset>
  <div className="form-navigation">{step>0&&<button type="button" className="button ghost" onClick={()=>setStep(v=>v-1)}>Retour</button>}{step<2?<button type="button" className="button" onClick={next}>Continuer</button>:<button className="button" type="submit">Envoyer la demande confidentielle</button>}</div><div role="status" className="form-status">{status}</div>
 </form>;
}
