import { notFound } from "next/navigation";
import { Check } from "lucide-react";
import { PageHero } from "@/components/PageHero";
import { ServiceJourney, type ServiceJourneyStep } from "@/components/ServiceJourney";
import { services } from "@/data/content";
import { pageMetadata } from "@/lib/site-metadata";
import type { Metadata } from "next";

const detailMap: Record<string, { challenge: string; included: string[]; owner: string[]; notIncluded: string[] }> = {
  "gestione-proprieta": { challenge: "Un seul interlocuteur pour votre bien.", included: ["Visite et prise en main du bien", "Calendrier et consignes réunis", "Réservations suivies", "Arrivées et départs coordonnés", "Prestataires organisés", "Nouvelles régulières au propriétaire"], owner: ["Un interlocuteur pour tout le bien", "Demandes et prestataires coordonnés", "Votre accord seulement quand il compte"], notIncluded: ["Ménage, linge et consommables facturés séparément", "Travaux engagés uniquement après validation selon le montant convenu"] },
  concierge: { challenge: "Vos voyageurs savent qui appeler.", included: ["Réponses sur le fonctionnement du bien", "Conseils adaptés au quartier", "Aide avec les équipements", "Informations sur les transports", "Prise en charge des imprévus", "Suivi jusqu’à la résolution"], owner: ["Les voyageurs savent qui appeler", "Les questions courantes ne vous reviennent plus", "Chaque imprévu est suivi jusqu’à sa résolution"], notIncluded: ["Achats, billets et réservations payés directement par le voyageur", "Pas de transport privé ni de restauration à domicile"] },
  "accoglienza-voyageurs": { challenge: "Chaque arrivée devient simple.", included: ["Message envoyé avant l’arrivée", "Accès et clés expliqués", "Bien contrôlé avant l’arrivée", "Accueil sur place ou à distance", "Équipements essentiels présentés", "Aide pendant l’installation"], owner: ["Les accès sont expliqués avant l’arrivée", "Les voyageurs s’installent sans vous appeler", "Une personne reste disponible au démarrage"], notIncluded: ["Transport et bagagerie non inclus", "Arrivées tardives organisées selon les conditions convenues"] },
  "pulizie-biancheria": { challenge: "Un bien propre, prêt à recevoir.", included: ["Liste de contrôle pièce par pièce", "Ménage planifié entre les séjours", "Linge propre coordonné", "Résultat vérifié après le ménage", "Consommables complétés selon l’inventaire", "Anomalies signalées au propriétaire"], owner: ["Le ménage suit une liste de contrôle", "Linge et consommables sont vérifiés", "Le bien est contrôlé avant l’arrivée"], notIncluded: ["Ménage, linge et consommables facturés séparément", "Nettoyages spécifiques proposés selon le besoin"] },
  manutenzione: { challenge: "Chaque imprévu devient une action.", included: ["Problème identifié", "Artisan adapté recherché", "Devis soumis avant engagement", "Accès au bien organisé", "Intervention suivie sur place", "Compte rendu et justificatifs transmis"], owner: ["Le problème est qualifié avant toute dépense", "Vous validez le devis si nécessaire", "Velyo suit l’artisan jusqu’à la résolution"], notIncluded: ["Main-d’œuvre, pièces et matériaux facturés séparément", "Délais soumis à la disponibilité réelle des artisans"] },
  "revenue-management": { challenge: "Louer au bon rythme.", included: ["Quartier et saison observés", "Tarifs adaptés aux périodes", "Durées minimales ajustées", "Réservations suivies", "Prix revus avec mesure", "Choix expliqués au propriétaire"], owner: ["Les tarifs suivent la saison", "Vos périodes restent prioritaires", "Chaque ajustement peut être expliqué"], notIncluded: ["Aucun revenu minimum garanti", "Toute projection reste indicative jusqu’à l’analyse du bien"] },
  sicurezza: { challenge: "Votre bien reste suivi.", included: ["État initial du bien noté", "Clés et accès suivis", "Vérification après chaque séjour", "Écarts signalés", "Conduite à tenir en cas d’incident", "Équipements essentiels contrôlés"], owner: ["Les clés et les accès restent suivis", "Tout écart important vous est signalé", "La prochaine action est clairement identifiée"], notIncluded: ["Velyo ne remplace ni une assurance ni un service d’urgence", "Toute réparation payante est proposée avant engagement"] },
  amministrazione: { challenge: "Tout le suivi au même endroit.", included: ["Réservations regroupées", "Prestations enregistrées", "Justificatifs classés", "Activité résumée clairement", "Incidents conservés dans l’historique", "Décisions importantes retrouvables"], owner: ["Réservations, dépenses et interventions réunies", "Un point envoyé au rythme convenu", "L’historique reste facile à retrouver"], notIncluded: ["Conseil fiscal, comptable ou juridique non inclus", "Documents spécialisés à valider avec les professionnels concernés"] },
};

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params;
  const service = services.find((item) => item.slug === slug);
  return service ? pageMetadata({ title: service.title, description: service.short, path: `/servizi/${slug}`, image: service.image }) : {};
}

export default async function Page({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const service = services.find((item) => item.slug === slug);
  if (!service) notFound();
  const details = detailMap[slug] || detailMap["gestione-proprieta"];
  const steps: ServiceJourneyStep[] = [
    { title: "Auditer le bien", timing: "01 · Découverte", text: "Nous visitons le bien, relevons son fonctionnement réel et identifions ce qui doit être repris.", points: ["Accès et équipements vérifiés", "Habitudes du lieu notées", "Priorités du propriétaire recueillies"] },
    { title: "Cadrer le service", timing: "02 · Organisation", text: "Le rôle de Velyo, les dépenses séparées et les décisions qui restent les vôtres sont posés clairement.", points: ["Périmètre écrit", "Budget et seuils définis", "Rythme des nouvelles choisi"] },
    { title: "Préparer l’exploitation", timing: "03 · Mise en place", text: "Nous réunissons les accès, les contacts, les consignes et le calendrier avant de recevoir.", points: ["Intervenants coordonnés", "Consignes centralisées", "Premier séjour préparé"] },
    { title: "Piloter les séjours", timing: "04 · Au quotidien", text: "Velyo suit les réservations, fait avancer les demandes et garde une vue d’ensemble sur le bien.", points: ["Voyageurs accompagnés", "Prestataires suivis", "Imprévus traités"] },
    { title: "Mesurer et ajuster", timing: "05 · Optimisation", text: "Les résultats, les écarts et les retours servent à améliorer l’organisation et la rentabilité dans la durée.", points: ["Activité relue", "Tarifs et processus ajustés", "Compte rendu utile"] },
  ];
  return <>
    <PageHero label={service.category} title={service.title} text={service.short} image={service.image} />
    <section className="detail-page-opening"><div className="container detail-opening-grid"><div className="detail-opening-copy"><p className="eyebrow">Ce que Velyo prend en charge</p><h2>{details.challenge}</h2><p>{service.short}</p></div><div className="detail-impact-strip">{details.owner.map((item, index) => <article key={item}><span>{String(index + 1).padStart(2, "0")}</span><strong>{item}</strong></article>)}</div></div></section>
    <section className="detail-process-section"><div className="container detail-process-heading"><div className="detail-process-title"><p className="eyebrow">Notre méthode</p><h2>Du diagnostic<br/><em>à la performance.</em></h2></div><div className="detail-process-intro"><span aria-hidden="true">01—07</span><p>Sept étapes structurent la prise en charge : comprendre le bien, préparer sa mise en location, piloter les séjours, suivre les résultats et améliorer ce qui doit l’être.</p></div></div><ServiceJourney steps={steps} /></section>
    <section className="detail-scope-section"><div className="container detail-scope-grid"><div><p className="eyebrow">Le périmètre concret</p><h2>Chaque action produit un résultat vérifiable.</h2><p className="detail-section-intro">Chaque action a un responsable, un moment et un résultat attendu.</p><div className="detail-scope-list">{details.included.map((item, index) => <article key={item}><span>{String(index + 1).padStart(2, "0")}</span><p>{item}</p></article>)}</div></div><aside className="detail-value-panel"><p className="eyebrow">Pour vous</p><h3>La gestion avance sans vous retirer les décisions.</h3><ul>{details.owner.map((item) => <li key={item}><Check size={16}/>{item}</li>)}</ul></aside></div></section>
    <section className="detail-clarity-section"><div className="container detail-clarity-grid"><div><p className="eyebrow">Une proposition lisible</p><h2>Tout est clair<br/>avant de commencer.</h2><p>Nous séparons ce que Velyo coordonne, ce qui est facturé au réel et ce qui demande votre accord.</p></div><div className="detail-rules"><div><span>Inclus</span><strong>Organisation, suivi et compte rendu du service</strong></div>{details.notIncluded.map((item, index) => <div key={item}><span>{index === 0 ? "À prévoir séparément" : "Selon la situation"}</span><strong>{item}</strong></div>)}<div><span>Votre décision</span><strong>Vous validez toute dépense ou action importante.</strong></div></div></div></section>
  </>;
}
